# Generated by Django 4.1 on 2023-06-09 13:05

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import src.apps.product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_is_main_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='product.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=src.apps.product.models.get_slug_value, slugify=src.apps.product.models.get_slugify_value, unique=True),
        ),
    ]
